# Generated by Django 3.0.6 on 2020-06-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveScorer', '0002_auto_20200609_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
