# Generated by Django 3.0.6 on 2020-06-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveScorer', '0003_competitions_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
