# Generated by Django 3.0.6 on 2020-06-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveScorer', '0004_competitions_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitions',
            name='description',
        ),
    ]
