# Generated by Django 3.0.6 on 2020-06-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ontop',
            field=models.BooleanField(default=False),
        ),
    ]
