# Generated by Django 3.0.6 on 2020-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_ontop'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
