# Generated by Django 3.0.6 on 2020-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200602_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
