# Generated by Django 3.0.6 on 2020-06-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='main',
        ),
    ]
